pipeline {
    agent any
    environment {
        DOCKER_IMAGE_NAME = "nagabhushanamn/client"
    }
    tools {nodejs "node"}
    stages {
        stage('Build') {
             steps {
              dir('client') {
                sh 'npm install'
                sh 'npm test'
              }
            }
        }
        stage('Build Docker Image') {
            steps {
              dir('client') {
                script {
                    app = docker.build(DOCKER_IMAGE_NAME)
                }
              }
            }
        }
        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
                        app.push("${env.BUILD_NUMBER}")
                        //app.push("latest")
                    }
                }
            }
        }
        stage('DeployToProduction') {
            steps {
                input 'Deploy to Production?'
                milestone(1)
                //implement Kubernetes deployment here
            }
        }
    }
}
