export const LOADER = 'LOADER';
export const SUBSCRIBE = 'SUBSCRIBE';
export const REQUEST_BEGIN = 'REQUEST_BEGIN';
export const REQUEST_FINISH = 'REQUEST_FINISH';
export const LOAD_PROMOTIONAL_VIDEOS = 'LOAD_PROMOTIONAL_VIDEOS';
export const LOAD_SOCIAL_FEEDS = 'LOAD_SOCIAL_FEEDS';
export const SHOW_MAIN_MENU = 'SHOW_MAIN_MENU';
export const COLLAPSE_MAIN_MENU = 'COLLAPSE_MAIN_MENU';
export const EXPAND_MAIN_MENU = 'EXPAND_MAIN_MENU';
export const HIDE_MAIN_MENU = 'HIDE_MAIN_MENU';
export const FETCH_TWITTER_FEED = 'FETCH_TWITTER_FEED';
export const FETCHED_TWITTER_FEED = 'FETCHING_TWITTER_FEED';

export const LOAD_CATEGORIES = 'LOAD_CATEGORIES';