version: '3'
services:
  api:
    build: ./api-server
    ports:
    - "8080:8080"
  client: 
    build: ./client
    ports:
     - "3000:3000"
  db:
   image: mongo
   ports:
      - "27017:27017"


